name = "newsnow"
pages_build_output_dir = "public"
compatibility_date = "2024-10-03"

[[d1_databases]]
binding = "NEWSNOW_DB"
database_name = "newsnow-db"
database_id = "b72d92d1-4aa7-437e-8255-fabb8585813e"
